### PR TITLE
Infra 3933 - Fix mobile UI of toolbar dropdown

### PR DESCRIPTION
**Pull request by flora8984461**
Part of https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=3933

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by ericpoirier** [comment]
Hi Yi,

Can you provide a screenshot of what it looks like with these styles?

Thanks.

**Comment by flora8984461** [comment]
> Hi Yi,
> 
> Can you provide a screenshot of what it looks like with these styles?
> 
> Thanks.

I created the ticket in Infra: https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=3933

it contains actually 2 issues: 
1) the toolbar dropdown causing extra right space and it happens all sites using toolbar
2) The Stats number in homepage(eclipse.org) causing extra right space 

For 2) I created a patch in https://git.eclipse.org/r/c/www.eclipse.org/home/+/172326

The issues screenshot:
1) the toolbar dropdown causing right space
image


2) The Stats number in homepage(eclipse.org) causing extra right space
image

After my fixes:
1) Fix the toolbar dropdown causing right space (I cannot log in to https://eclipse.php53.dev.docker/home/ or login to localhost:1313 so that cannot provide a screenshot for that), I'm showing the two Hugo sites that have language selector:
image
image


2) Fix the Stats number in homepage(eclipse.org) causing extra right space
image

**Review by ericpoirier — APPROVED** [review]

**Comment by flora8984461** [comment]
Btw, can you guys login on localhost to test the `my accounts'` dropdown? 🤔 When I click on login it leads me to accounts.eclipse.org on my localhost which I'm not sure if I'm ready to install the drupal site

**Review by chrisguindon — CHANGES_REQUESTED** [review]
I am curious to see this working with 2 dropdowns. 

My concern is that both dropdowns will be right-aligned and I am not sure this is what we want.

Can you hardcode a new fake dropdown?


```
<li class="dropdown">
  <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome, Test User <span class="caret"></span></a>
  <ul class="dropdown-menu toolbar-dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><a href="https://www.eclipse.org/user/webdev"><i class="fa fa-user"></i> View Profile</a></li>
    <li><a href="https://accounts.eclipse.org/user/edit" class="" data-tab-destination="tab-profile"><i class="fa fa-edit"></i> Edit Profile</a></li>
    <li class="divider"></li>
    <li><a class="toolbar-manage-cookies dropdown-toggle"><i class="fa fa-wrench"></i> Manage Cookies</a></li>
    <li class="divider"></li>
    <li><a href="https://accounts.eclipse.org/user/logout"><i class="fa fa-sign-out"></i> Log out</a></li>
  </ul>
</li>

```

**Pull request merged**
