### PR TITLE
Update assets compilation to properly use Babel transpiling + shims

### PR DESCRIPTION
**Pull request by autumnfound**
Previously, we were using mix.babel() to compile JS files. As this runs
the files through a Babel engine and concats, but doesn't properly shim
the code for ES5. The JS command will transpile with Babel, pull in
proper configs, and shim the code as well.

Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
This PR would require changes in the repositories to fix the babel configs due to how the webpack JS loads the configuration. The change would require a rename of `babel.config.json` to `.babelrc`, and an update to the path for the extends path to point at the new file name.

**Comment by flora8984461** [comment]
https://deploy-preview-224--eclipsefdn-solstice-assets.netlify.app/ I think the js is not working on the normal browsers.
 
```
solstice.js:2 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at Object.2666 (solstice.js:2)
    at n (solstice.js:2)
    at s (solstice.js:2)
    at Function.n.x (solstice.js:2)
    at solstice.js:2
    at solstice.js:2
```

**Comment by autumnfound** [comment]
> https://deploy-preview-224--eclipsefdn-solstice-assets.netlify.app/ I think the js is not working on the normal browsers.
> 
> ```
> solstice.js:2 Uncaught Error: Bootstrap's JavaScript requires jQuery
>     at Object.2666 (solstice.js:2)
>     at n (solstice.js:2)
>     at s (solstice.js:2)
>     at Function.n.x (solstice.js:2)
>     at solstice.js:2
>     at solstice.js:2
> ```

Looks like uglify compression is acting up...going to see if I can disable that

**Comment by autumnfound** [comment]
So the issue isn't uglify. Looking into this, it seems like each file is treated as a module and containerized in a way. This breaks global namespacing that a lot of our code relies on. There are ways to fix this, but we will need to configure the `ProvidePlugin` to make use of globals properly. 

Another way we can do to fix this is to not process the vendor files at all to avoid some of the worst issues with the modular containers (jquery access seems to be a big one that breaks often enough). We would still need to make sure that scripts that require assets from outside their own file have been given access through the provide plugin, but we wouldn't have to worry about as much access.

**Comment by autumnfound** [comment]
After discussion with Chris, we will be moving away from Babel for the current theme. There seems to be some strange semantics at play with the js compile that doesn't play well with our structure. With how few es6 features we use, we would be better served just making everything es5 until we drop IE support

**Pull request closed without merging**
