### PR TITLE
Add badge notifications

### PR DESCRIPTION
**Pull request by ericpoirier**
Change-Id: Ifb5c2f536bcf933a256e4a42cd9071d233cece67
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Review by autumnfound — COMMENTED** [review]
Would we maybe want notification badges to have configurable colors as variables?

**Comment by ericpoirier** [comment]
> Would we maybe want notification badges to have configurable colors as variables?

I would probably be a good idea.

I can add variables in there to make it more configurable.

**Comment by flora8984461** [comment]
other than what Martin mentioned, where will badge notifications show? Will there be another PR for it?

**Comment by ericpoirier** [comment]
> other than what Martin mentioned, where will badge notifications show? Will there be another PR for it?

I'm using the badge notification in the PMI. This is the only website where notifications are active.

Screen Shot 2021-01-06 at 9 00 00 AM

**Pull request merged**
