### PR TITLE
Add fix for fullscreen youtube videos in HTML5 in jS

### PR DESCRIPTION
**Pull request by autumnfound**

### CODE REVIEW

**Comment by autumnfound** [comment]
This fix can be tested on the Netlify page by accepting cookies and trying to view the video content at the bottom of the page in fullscreen.

**Review by ericpoirier — APPROVED** [review]

**Comment by aeiras** [comment]
Hola Martin, 

I see it, looks Ok from this side. Are there anything we should know about longterm mantainance with youtube contributions within the release pages?

Happy 1st of June, lets end Q2 rocking it! :)

**Comment by autumnfound** [comment]
> Hola Martin,
> 
> I see it, looks Ok from this side. Are there anything we should know about longterm mantainance with youtube contributions within the release pages?
> 
> Happy 1st of June, lets end Q2 rocking it! :)

Hi Amelia!

This was just a long-overdue fix that was never noticed until now. We make use of Youtube's embedding code, so as long as YouTube keeps the way they embed the same, this is a very low-maintenance implementation! As long as all of the videos make use of the `eclipsefdn-video` class in the HTML like how it's done on jakarta.ee/release/9, this little bit of code will take care of the rest.

Does that address your concerns around this?

**Comment by aeiras** [comment]
Yes, how wonderful. 
Youtube will change stuff but hopefully we are head of the fix and keep up with the "innovation" they might throw to users. 

Sounds wonderful, lets close this. Super fun to collaborate with you and the team as usual Martin. Hugs

**Pull request merged**
