### PR TITLE
Add main sidebar styles for Quicksilver

### PR DESCRIPTION
**Pull request by ericpoirier**
Change-Id: I588a135554529922f2599869fca5fcd166d173e9
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Review by flora8984461 — CHANGES_REQUESTED** [review]
I think the folder path is not corresponding, one is under ` less/_components/quicksilver/` while the import is `../_components/main-sidebar.less`

**Comment by autumnfound** [comment]
Are we still using this PR?

**Comment by chrisguindon** [comment]
@ericpoirier can we close this?

**Comment by chrisguindon** [comment]
> @ericpoirier can we close this?

Eric, can we close this? If not, can we finish this?

**Comment by ericpoirier** [comment]
> > @ericpoirier can we close this?
> 
> Eric, can we close this? If not, can we finish this?

I'll rebase and see if there is more work to be done to close this.

**Review by autumnfound — APPROVED** [review]

**Comment by chrisguindon** [comment]
As a side note, I started to use this new sidebar on newer sites:
https://eclipsefdn-osgi.netlify.app/about/faq/
https://eclipsefdn-asciidoc.netlify.app/about/

..whatever solution we take, we must make sure not to break older sites with the previous sidebar such as https://jakarta.ee/about/

**Pull request merged**
